site_name: Estructura LOOM de explicación del sistema
theme:
  name: material

nav:
  - Inicio: index.md
  - Introducción: intro.md
  - CRM:
      - Movimiento en el pipeline: CRM/movimientopipeline.md
      - Agregar Notas: CRM/aggnotas.md
      - Etiquetas: CRM/etiquetas.md
      - Filtrar: CRM/filtrar.md
  - Conversaciones:
      - Etiquetas, pipeline, asignacion de user, notas: Conversaciones/Etiq,pipeline,au,notas.md
      - Favoritos: Conversaciones/favoritos.md
      - Filtro pot palabra, nombre o número de teléfono: Conversaciones/filtropor.md
  - Dashboard:
      - Filtro: Dashboard/Filtropor.md
  - Calendarios:
      - Parte 1: Calendarios/calendario.md
      - Parte 2: Calendarios/calendario.md



