site_name: Tutoriales de MedIASys System
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan 
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Inicio: index.md
  - Introducción: intro.md
  - CRM:
      - Procedimiento Estandar: CRM/procedimientoCRM.md
      - Otros: CRM/otrosCRM.md
  - Conversaciones:
      - Procedimiento Estandar: Conversaciones/conversaciones.md
      - Favoritos: Conversaciones/Favoritos.md
  - Dashboard:
      - Procedimiento Estandar: Dashboard/procedimientodashboard.md
      - Otros: Dashboard/filtrodashboard.md
  - Calendarios:
      - Procedimiento Estandar: Calendarios/calendario.md
      - Otros: Calendarios/calendario.md






